# Generated by Django 5.2.7 on 2025-10-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgy_app', '0002_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
    ]
