# Generated by Django 5.2.7 on 2026-05-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgy_app', '0004_budget_user_expenses_user_incomes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='img',
        ),
        migrations.CreateModel(
            name='ExpenseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='expense_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='budgy_app.expenses')),
            ],
        ),
    ]
